---
deployment:
  tasks:
    - export DEPLOYPATH=/home/metaches/metaMain # ← مسیر واقعی ریپو
    - cd "$DEPLOYPATH"
    - /bin/node -v && /bin/npm -v
    - /bin/npm ci --omit=dev || /bin/npm i --omit=dev
    - /bin/mkdir -p tmp
    - npm run build # → react/dist ساخته می‌شود
    - /bin/echo "Restarting app…"
    - /bin/touch tmp/restart.txt # سیگنال ری‌استارت Passenger

