name: CI / build-and-verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# در صورت چند بار پوش پیاپی روی یک شاخه، رَن‌های قبلی لغو شوند
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Prettier check
        run: npm run format:check

      # اگر بعداً تست‌ها را اضافه کردید، این مرحله را فعال کنید:
      # - name: Tests
      #   run: npm test

      # اگر کاوریج اضافه شد:
      # - name: Coverage
      #   run: npm run coverage

      # نمونه آپلود آرتیفکت (گزارش کاوریج/لاگ‌ها) — اختیاری
      # - name: Upload artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ci-artifacts-node-${{ matrix.node }}
      #     path: |
      #       coverage/**
      #       logs/**
